#
# Generated - do not edit!
#
# NOCDDL
#
CND_BASEDIR=`pwd`
# pic32mz_w1_curiosity_wolfcrypt configuration
CND_ARTIFACT_DIR_pic32mz_w1_curiosity_wolfcrypt=dist/pic32mz_w1_curiosity_wolfcrypt/production
CND_ARTIFACT_NAME_pic32mz_w1_curiosity_wolfcrypt=ota_bootloader_wolfcrypt.X.production.hex
CND_ARTIFACT_PATH_pic32mz_w1_curiosity_wolfcrypt=dist/pic32mz_w1_curiosity_wolfcrypt/production/ota_bootloader_wolfcrypt.X.production.hex
